server:
  port: 8090
# DataSource Config
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/eblog?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC

# 打印sql语句
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/eblog?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: eblog
    password: eblog
  freemarker:
    settings:
#      classtic_compatible: true #处理空值
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  redis:
    host: localhost
    port: 6379
    password:
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
file:
  upload:
    dir: ${user.dir}/upload
